from abc import ABC, abstractmethod
class BaseLLMProvider(ABC):
    @abstractmethod
    def generate_text(self, prompt: str, **kwargs: object) -> str: ...
    def generate_json(self, prompt: str, **kwargs: object) -> dict: ...
